<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>

        <ApplicationIcon>Assets\avalonia-logo.ico</ApplicationIcon>
        <AssemblyVersion>0.1.0</AssemblyVersion>
        <Version>0.1.0</Version>
        <FileVersion>0.1.0</FileVersion>
        <InformationalVersion>Haskoli UI</InformationalVersion>

    </PropertyGroup>

    <ItemGroup>
        <Folder Include="Models\" />
        <AvaloniaResource Include="Assets\**" />
        <None Remove="appsettings.json" />
        <Content Include="appsettings.json">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
          <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
          <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
        </Content>
        <Folder Include="ServicesCollection\" />
    </ItemGroup>


    <ItemGroup>
        <PackageReference Include="AutoMapper" Version="16.2.0" />

        <PackageReference Include="Avalonia" Version="12.1.0" />
        <PackageReference Include="Avalonia.Desktop" Version="12.1.0" />
        <PackageReference Include="Avalonia.Themes.Fluent" Version="12.1.0" />
        <PackageReference Include="Avalonia.Fonts.Inter" Version="12.1.0" />
        <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
        <PackageReference Condition="'$(Configuration)' == 'Debug'" Include="Avalonia.Diagnostics" Version="11.3.18" />
        <PackageReference Include="Avalonia.ReactiveUI" Version="11.3.8" />
        <PackageReference Include="MessageBox.Avalonia" Version="12.0.0" />

        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.10" />

        <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
        <PackageReference Include="Serilog.Settings.AppSettings" Version="3.0.0" />
        <PackageReference Include="Serilog.Settings.Configuration" Version="10.0.1" />
        <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
        <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
        <PackageReference Include="Serilog.Sinks.MSSqlServer" Version="10.0.0" />
        <PackageReference Include="Serilog.Sinks.Seq" Version="9.1.0" />
        <PackageReference Include="SkiaSharp" Version="4.150.1" />
        <PackageReference Include="SkiaSharp.NativeAssets.Linux" Version="4.150.1" />
        <PackageReference Include="SkiaSharp.NativeAssets.Linux.NoDependencies" Version="4.150.1" />
        <PackageReference Include="SkiaSharp.NativeAssets.Win32" Version="4.150.1" />
        <PackageReference Include="Stateless" Version="5.20.1" />

    </ItemGroup>


    <ItemGroup>
      <ProjectReference Include="..\Haskoli.Application\Haskoli.Application.csproj" />
      <ProjectReference Include="..\Haskoli.Domain\Haskoli.Domain.csproj" />
    </ItemGroup>
</Project>
